spring:
  sleuth:
    enabled: false
  datasource:
    url: jdbc:mysql://isocloud-db-mysql:3307/isocloud_zipkin?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: yxt1108
    schema: classpath:/mysql.sql
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5      #初始化连接个数
      max-active: 20       #最大连接个数
      min-idle: 5          #最小连接个数
      max-wait: 6000       #最大等待时间
      pool-prepared-statements: true                        #开启缓存PSCache
      max-pool-prepared-statement-per-connection-size: 20   #指定每个连接上PSCache的大小
      time-between-eviction-runs-millis: 6000               #在空闲连接回收器线程运行期间休眠的时间值
      min-evictable-idle-time-millis: 100000                # 配置一个连接在池中最小生存的时间
      validation-query: SELECT 1 FROM DUAL                  #用来检测连接是否有效的sql
      validation-query-timeout: 60000                       #检查sql超时时间
      test-while-idle: true     #申请连接的时候检测
      test-on-borrow: false     #申请连接时执行validationQuery检测连接是否有效
      test-on-return: false     #归还连接时执行validationQuery检测连接是否有效
      #开启StatFilter
      stat:
        enabled: true
        log-slow-sql: true
        slow-sql-millis: 1000
      #开启Slf4jFilter
      slf4j:
        enabled: true
        data-source-log-enabled: false
        connection-log-enabled: false
        statement-log-enabled: false
        result-set-log-enabled: false
      #开启WallFilter
      wall:
        enabled: true
        log-violation: true
        throw-exception: false
        config:
          delete-where-none-check: true
      #开启Web监控
      web-stat:
        enabled: true
      #开启Aop监控
      aop-stat:
        enabled: true
      #开启监控页面
      stat-view-servlet:
        enabled: true
        login-username: admin
        login-password: admin

zipkin:
  collector:
    rabbitmq:
      addresses: isocloud-rabbitmq:5672
      username: guest
      password: guest
      queue: zipkin

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
  metrics:
    web:
      server:
        auto-time-requests: false