spring:
  mvc:
    date-format: yyyy-MM-dd HH:mm:ss
  jackson:
    joda-date-time-format: yyyy-MM-dd HH:mm:ss
    date-format: yyyy-MM-dd HH:mm:ss
  datasource:
    url: jdbc:mysql://isocloud-db-mysql:3307/isocloud_tpc?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&allowMultiQueries=true
    username: root
    password: yxt1108
    driver-class-name: com.mysql.cj.jdbc.Driver
    filters: stat,wall
    druid:
      initial-size: 50
      min-idle: 50
      max-active: 100
      test-on-borrow: true
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      web-stat-filter:
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
      stat-view-servlet:
        allow:
        login-username: admin
        login-password: admin
# xxl 执行器配置
xxl:
  job:
    admin:
      addresses: http://192.168.2.21:30085/xxl-job-admin
    executor:
      appname: job_tpc
      ip:
      port: 9093
      logpath: /data/applogs/xxl-job/jobhandler
      logretentiondays: -1
    accessToken:

mybatis:
  type-aliases-package: com.isosaas.isocloud.service.uac.model
  mapper-locations: classpath:mapper/*.xml,classpath*:sdk/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

mapper:
  mappers: com.isosaas.isocloud.common.core.ibatis.BaseMapper
  not-empty: false
  identity: MYSQL

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql


rocketmq:
  # 生产者配置
  producer:
    instanceName: isocloud-service-tpc
    producerGroupName: TpcProducerGroup
    namesrvAddr: 127.0.0.1:9876
    # sendResult返回的sendStatus!=SEND_OK 是否重试
    retryAnotherBrokerWhenNotStoreOK: true
  # 消费者配置
  pushconsumer:
    instanceName: isocloud-service-tpc
    consumerGroupName: TpcPushConsumerGroup
    namesrvAddr: 127.0.0.1:9876
    topic: tpcTopic
    tags: tpcTags
