#spring:
#  boot:
#    admin:
#      client:
#        metadata:
#          user:
#            name: ${security.user.name}
#            password: ${security.user.password}
#      monitor:
#        period: 60000
#      discovery:
#        enabled: true
#      notify:
#        mail:
#          to: zhoubolong@szaisiou.com
#          from: zblcourage@126.com
#      turbine:
#        clusters: default
#        location: isocloud-monitor
#      routes:
#        endpoints: env,metrics,dump,jolokia,info,configprops,trace,logfile,refresh,flyway,liquibase,heapdump,loggers,auditevents,hystrix.stream
spring:
  security:
    user:
      name: admin
      password: admin
    basic:
      enabled: false
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS

turbine:
  app-config: isocloud-gateway #收集监控信息的服务名
  combine-host-port: true
  cluster-name-expression: new String('default') #集群名称